### ISSUE TITLE
Support for H3123

### ISSUE THREAD

**Issue by SQLSlacker** [sonyxperiadev/device-sony-pioneer#19]
Following Sony AOSP build guide and Xperia XA2 H3123 is not listed. H3113 and H3123 have different LTE bands. Please add H3123 to repo.

**Comment by bartcubbins** [comment]
adding h3123 here will not fix your issue

**Comment by titilambert** [comment]
@bartcubbins What do we have to do to fix this issue ?

**Comment by jerpelea** [comment]
duplicate h3113 in your local repo as h3123 and configure the userdata size if needed.
the bands are stored on the hardware and should not interfere with your images

**Comment by cherrycreek00** [comment]
I'm trying to get a used H3123 to work. I should flash H3113 image? Can you give any info on how to configure userdata size or why one might need to? Thanks :)

**Comment by jerpelea** [comment]
@cherrycreek00 
copy aosp_h3113.mk to as aosp_h3123.mk

add 3123 target in 
https://github.com/sonyxperiadev/device-sony-pioneer/blob/master/AndroidProducts.mk

edit the userdata size if needed
https://github.com/sonyxperiadev/device-sony-pioneer/blob/master/BoardConfig.mk#L39

Good luck
Alin
