### ISSUE TITLE
AOSP won't build, missing out/target/product/pioneer/obj/KERNEL_OBJ/usr

### ISSUE THREAD

**Issue by sbourdeauducq** [sonyxperiadev/device-sony-pioneer#38]
* following instructions at https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-android-11-0-0/
* obtained AOSP with ``repo init -u https://android.googlesource.com/platform/manifest -b android-11.0.0_r4``
* using branch ``android-11.0.0_r4`` of ``sonyxperiadev/local_manifests``, placed in ``.repo``
* selected ``aosp_h4113-eng`` during ``lunch``

``make`` fails with:

```
============================================
FAILED: ninja: 'out/target/product/pioneer/obj/KERNEL_OBJ/usr', needed by 'out/target/product/pioneer/obj/EXECUTABLES/ipacm_intermediates/IPACM_Main.o', missing and no known rule to make it
05:23:07 ninja failed with: exit status 1
```

**Comment by jerpelea** [comment]
please run repo_update.sh

**Comment by jerpelea** [comment]
all reports should be posted to https://github.com/sonyxperiadev/bug_tracker/
