### ISSUE TITLE
[H3113] Rear camera can be used only once

### ISSUE THREAD

**Issue by phpbg** [sonyxperiadev/device-sony-pioneer#39]
Hi,
I'm not sure if this is the right place for this issue.
Please let me know.

I just compiled Android 11 AOSP following your [official guide](https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-android-11-0-0) and installed latest official kernel [SW_binaries_for_Xperia_Android_11_4.14_v2a_nile.zip](https://developer.sony.com/file/download/software-binaries-for-aosp-android-11-0-kernel-4-14-nile/) on a Sony XA2 H3113.

Everything went fine, and phone works fine, except for the rear camera.
The camera always works fine when you use it for the first time after boot. But as soon as the camera was paused/shot down, it cannot be launched anymore, image is either black, or dark+green.

I tried many camera applications, they all behave the same, or don't work.

Spets to reproduce with AOSP camera app :
1. Launch the app : it should work
2. Go back home screen
3. Lauch camera again : screen remain black, or very dark/green, it is not possible anymore to take pictures

NB: front camera works fine

Regards

**Comment by jerpelea** [comment]
duplicate 
**https://github.com/sonyxperiadev/bug_tracker/issues/646**

**Comment by jerpelea** [comment]
please use the bug tracker!
