### ISSUE TITLE
[H3113] Phone reboot after call

### ISSUE THREAD

**Issue by phpbg** [sonyxperiadev/device-sony-pioneer#40]
On Android 11 AOSP on Sony XA2 H3113, phone reboots
* when you end a call,
* or when you receive an incoming call but don't answer, after the last ring

How to investigate and fix this?

**Comment by phpbg** [comment]
Please note that this bug happens only with `eng` (aka engineer) variant of build (selected at `lunch`).

I rebuilt AOSP using `user` (aka release) variant and I cannot reproduce it anymore.

**Comment by jerpelea** [comment]
please use the bug tracker
https://github.com/sonyxperiadev/bug_tracker/
